spring:
  datasource:
    url: jdbc:h2:file:./data/billsdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.alex.bills.model

server:
  port: 8080
